class Buttons:
    buy = 'Купить'
    sell = 'Продать'
    orders = 'Мои ордера'
    verify = 'Verify'
    wait = 'Wait'
    decline = 'Decline'
    back = 'Назад'
    allocation = 'allocation (locked tokens)'
    wl = 'whitelist'
    sn_account = 'social network account'
    unlocked_tokens = 'unlocked tokens (nft, testnet etc)'
    other = 'other'
    yes = 'Да'
    no = 'Нет'

